/*
 * This source file was generated by the Gradle 'init' task
 */
package vanilla_kafka;

import java.util.Properties;

import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.serialization.StringSerializer;

public class KafkaProducerExample {
    

    public static void main(String[] args) {


        // Configuración del productor de Kafka
        Properties props = new Properties();
        props.put("bootstrap.servers", "localhost:9093");
        props.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
        props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());


        // --- CONFIGURACIÓN DE SEGURIDAD SSL ---
        props.put("security.protocol", "SSL");
        
        // Ruta al archivo que creamos con keytool
        props.put("ssl.truststore.location", "C:/Users/PC/Desktop/Kafka/certificados/kafka.truststore.jks");
        props.put("ssl.truststore.password", "SISTEMASCENTRALESkey");


        // Crear el productor de Kafka
        Producer<String, String> producer = new KafkaProducer<>(props);


        // Enviar mensajes genéricos
        for (int i = 0; i < 10; i++) {
            producer.send(new ProducerRecord<>("test-topic", "key-" + Integer.toString(i), "mensaje-" + i));
        }

        producer.close();


    }
}
