/*
 * This source file was generated by the Gradle 'init' task
 */
package vanilla_kafka;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


public class AppTest {
    @Test
    public void testApp() {
        assertTrue(true);
    }
}
